apiVersion: v1
data:
  input_main.conf: |-
    input {
      # udp {
      #   port => 1514
      #   type => syslog
      # }
       tcp {
         port => 1514
         type => syslog
         codec => json
       }
      beats {
        port => 5044
      }
      # http {
      #   port => 8080
      # }
      # kafka {
      #   ## ref: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
      #   bootstrap_servers => "kafka-input:9092"
      #   codec => json { charset => "UTF-8" }
      #   consumer_threads => 1
      #   topics => ["source"]
      #   type => "example"
      # }
    }
  output_main.conf: |-
    output {
      # stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        manage_template => false
       # truststore  => "/usr/share/logstash/config/trustore/file"
        cacert => "/usr/share/logstash/config/elasticsearch-certs/tls.crt"
        user => "elastic"
        password => "5bl84dhs5n9jrppj5phnjm6j"
        index => "logstash-%{+YYYY.MM.dd}"
      }
      # kafka {
      #   ## ref: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html
      #   bootstrap_servers => "kafka-output:9092"
      #   codec => json { charset => "UTF-8" }
      #   compression_type => "lz4"
      #   topic_id => "destination"
      # }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-10-09T17:09:35Z"
  labels:
    app: logstash
    chart: logstash-2.3.0
    heritage: Tiller
    release: logstash-helm
  name: logstash-helm-pipeline
  namespace: default
  resourceVersion: "267401"
  selfLink: /api/v1/namespaces/default/configmaps/logstash-helm-pipeline
  uid: 91efa418-eab7-11e9-8e09-862853a7f922
