apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash-sa

## kubectl create rolebinding logstash-admin --clusterrole=admin --serviceaccount=default:logstash-sa  
## kubectl create clusterrolebinding logstash-tiller-cluster --clusterrole=admin --serviceaccount=kube-system:default
## helm install -f elk\logstash\logstash-helm-values.yaml --name logstash-helm stable/logstash