apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elk
spec:
  version: 7.4.2
  nodes:
  - nodeCount: 2
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1024M -Xmx1024M
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 2
        nodeSelector:
          type: compute
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi              
        #storageClassName: standard # can be any available storage class	
  http: 
    service:
      #properties:
      #  metadata:
      #    annotations: 
      #      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: ClusterIP		
